source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'APMAlertController_Example' do
  pod "APMAlertController", :path => "../"

  target 'APMAlertController_Tests' do
    inherit! :search_paths
  end
end