# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
rvm:
  - 2.2.3
osx_image: xcode7.2
xcode_workspace: Example/APMAlertController.xcworkspace
xcode_scheme: APMAlertController-Example
xcode_sdk: iphonesimulator9.2
cache: cocoapods
podfile: Example/Podfile
before_install:
  - brew update
# - brew install xctool
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
  - xctool -workspace Example/APMAlertController.xcworkspace -scheme APMAlertController-Example -sdk iphonesimulator9.2 -destination 'platform=iOS Simulator,name=iPhone 6s' ONLY_ACTIVE_ARCH=NO clean build
#- set -o pipefail && xcodebuild build -workspace Example/APMAlertController.xcworkspace -scheme APMAlertController-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
