language: objective-c
osx_image: xcode9
xcode_sdk: iphoneos11.0
cache: bundler
script:
    - bundle install
    - bundle exec fastlane test
after_success:
    - bash <(curl -s https://codecov.io/bash) -J 'APMAlertController'
