language: objective-c
osx_image: xcode8.2
xcode_sdk: iphoneos10.2
before_script:
    - 'if [ ${TRAVIS_SECURE_ENV_VARS} = "true" ]; then
          bundle exec danger;
      fi'
script:
    - brew update
    - brew upgrade swiftlint
    - bundle install
    - bundle exec fastlane test
