devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
  "iPad Retina"
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme "APMAlertController-Example"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

clear_previous_screenshots true

# Choose which project/workspace to use
workspace "./APMAlertController.xcworkspace"
