#!usr/bin/ruby

fastlane_version '2.0'

default_platform :ios

platform :ios do
  before_all do
    ENV['FASTLANE_XCODE_LIST_TIMEOUT'] = '120'
  end

  desc 'Run tests'
  lane :test do
    scan(
      project: 'APMAlertController.xcodeproj',
      scheme: 'APMAlertController',
      clean: true,
      code_coverage: true,
      formatter: 'xcpretty-json-formatter'
    )
  end
end
